### ISSUE TITLE
I can create an issue

### ISSUE THREAD

**Issue by KevinOConnor** [Arksine/moontest#3]
It is still possible to create issues in this repo.

-Kevin

**Comment by M0rus** [comment]
Hi, at first
I'm a new member here so i do not know i'm right here.
i set my printer with klipper last week. my problem, the printer shut down after homeing stepper_z.
i read about problems like these in issue #5241, but it doesn't help me.
Is there anybody out there helping me?
-Morus

**Comment by M0rus** [comment]
Hi Kevin,
it seams I'm not the not the brightest candle on the cake.
i do not understand how I create a issue. The issue I read is closed!
I'm a bloody rockie on GitHub and not nativ english speaking, may that's caused my problems.
May you help me again?
-thanks 
M0rus
